#!/usr/bin/env python3
"""Export a trained model to ONNX and check its output against torch.

Why ONNX: on Windows torch drags one and a half to two gigabytes into the
bundle, onnxruntime-directml about a hundred megabytes. The model itself is
hundreds of megabytes, which is enough; adding torch on top is pointless.

The spatial axes are declared dynamic: the tile may change, and on small
frames it pays to run the whole volume at once. Divisibility is the caller's
job (deploy/dental9/infer.py) — the network downsamples five times on the
first axis and six on the others, hence the (32, 64, 64) divisor.

Deep supervision is switched off for export: the extra heads are only needed
for training, in the graph they would be one extra output.

Usage:
    python3 deploy/scripts/export_onnx.py \
        --ckpt server_backup/checkpoint_best.pth \
        --plans nnUNet_preprocessed/Dataset003_Dental9/nnUNetResEncL_p160x320x320.json \
        --out deploy/models/dental9.onnx
"""
import argparse
import json
import os
import time

import numpy as np
import onnx
import torch
import torch.nn as nn
from dynamic_network_architectures.architectures.unet import ResidualEncoderUNet


def build_network(plans: dict, num_classes: int) -> nn.Module:
    """Exactly the network described in the plans. Nothing is substituted:
    a mismatch in a single field and the weights will not load."""
    ak = plans["configurations"]["3d_fullres"]["architecture"]["arch_kwargs"]
    return ResidualEncoderUNet(
        input_channels=1,
        n_stages=ak["n_stages"],
        features_per_stage=ak["features_per_stage"],
        conv_op=nn.Conv3d,
        kernel_sizes=ak["kernel_sizes"],
        strides=ak["strides"],
        n_blocks_per_stage=ak["n_blocks_per_stage"],
        num_classes=num_classes,
        n_conv_per_stage_decoder=ak["n_conv_per_stage_decoder"],
        conv_bias=ak["conv_bias"],
        norm_op=nn.InstanceNorm3d,
        norm_op_kwargs=ak["norm_op_kwargs"],
        dropout_op=None,
        nonlin=nn.LeakyReLU,
        nonlin_kwargs={"inplace": True},
        deep_supervision=False,
    )


def tile_divisor(plans: dict) -> list:
    """The product of the strides per axis — the tile must be divisible by it.
    dental9 has (32, 64, 64), the tooth-numbering model (32, 32, 32); a
    constant here would break on the first new architecture."""
    strides = plans["configurations"]["3d_fullres"]["architecture"]["arch_kwargs"]["strides"]
    d = [1, 1, 1]
    for s in strides:
        d = [a * int(b) for a, b in zip(d, s)]
    return d


def make_config(plans: dict, model_name: str, num_classes: int, ck: dict) -> dict:
    c = plans["configurations"]["3d_fullres"]
    fp = plans["foreground_intensity_properties_per_channel"]["0"]
    return {
        "_comment": "Generated by deploy/scripts/export_onnx.py from the nnUNet plans. Do not edit by hand.",
        "model": model_name,
        "dataset": plans.get("dataset_name", "Dataset003_Dental9"),
        "epoch": int(ck.get("current_epoch", -1)),
        "orientation": "LPS",
        "spacing": round(float(c["spacing"][0]), 6),
        "train_patch": [int(v) for v in c["patch_size"]],
        "tile": [int(v) for v in c["patch_size"]],
        "tile_divisor": tile_divisor(plans),
        "overlap": 0.5,
        "num_classes": int(num_classes),
        "normalization": {
            "scheme": c["normalization_schemes"][0],
            "clip": [float(fp["percentile_00_5"]), float(fp["percentile_99_5"])],
            "mean": float(fp["mean"]),
            "std": float(fp["std"]),
        },
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", required=True)
    ap.add_argument("--plans", required=True)
    ap.add_argument("--out", default="deploy/models/dental9.onnx")
    ap.add_argument("--classes", type=int, default=10, help="number of network outputs: classes plus background")
    ap.add_argument("--extra-config", default=None,
                    help="JSON whose fields are added to the config next to the weights "
                         "(e.g. the tooth numbering scheme)")
    ap.add_argument("--check-tile", type=int, nargs=3, default=[64, 128, 128],
                    help="tile on which to compare torch and ONNX; small to keep it fast")
    ap.add_argument("--opset", type=int, default=17)
    ap.add_argument("--precision", choices=("fp16", "fp32"), default="fp16",
                    help="fp16 halves the file and is a quarter faster on the GPU; "
                         "quality measured, no difference")
    a = ap.parse_args()

    plans = json.load(open(a.plans))
    ck = torch.load(a.ckpt, map_location="cpu", weights_only=False)
    print(f"checkpoint: epoch {ck.get('current_epoch', '?')}, "
          f"EMA {ck.get('_best_ema', float('nan')):.4f}")

    net = build_network(plans, a.classes).eval()
    # Checked by hand: silently swallowing a weight mismatch is the worst
    # thing that can happen here, because the model would still predict
    # something.
    missing, unexpected = net.load_state_dict(ck["network_weights"], strict=False)
    if missing or unexpected:
        # deep supervision is off, so extra decoder heads are expected
        extra = [k for k in unexpected if ".seg_layers." not in k]
        absent = [k for k in missing if ".seg_layers." not in k]
        if extra or absent:
            raise SystemExit(f"weights do not match the architecture:\n"
                             f"  missing from checkpoint: {absent[:5]}\n"
                             f"  unexpected: {extra[:5]}")
        print(f"deep supervision heads dropped: {len(unexpected)} tensors")
    print(f"parameters in the graph: {sum(p.numel() for p in net.parameters())/1e6:.0f} M")

    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    tile = tuple(a.check_tile)
    x = torch.randn(1, 1, *tile)

    print(f"exporting to {a.out} ...")
    t0 = time.time()
    torch.onnx.export(
        net, x, a.out,
        input_names=["input"], output_names=["logits"],
        dynamic_axes={"input": {2: "d", 3: "h", 4: "w"},
                      "logits": {2: "d", 3: "h", 4: "w"}},
        opset_version=a.opset, do_constant_folding=True,
    )
    size = os.path.getsize(a.out) / 1e6
    print(f"done in {time.time()-t0:.0f} s, file {size:.0f} MB")

    # --- check: ONNX must reproduce torch, otherwise the export is pointless ---
    import onnxruntime as ort  # noqa: PLC0415
    with torch.no_grad():
        ref = net(x).numpy()
    sess = ort.InferenceSession(a.out, providers=["CPUExecutionProvider"])
    got = sess.run(None, {"input": x.numpy()})[0]
    diff = np.abs(ref - got)
    same_label = (ref.argmax(1) == got.argmax(1)).mean()
    print(f"check on tile {tile}:")
    print(f"  max logit difference:   {diff.max():.2e}")
    print(f"  mean logit difference:  {diff.mean():.2e}")
    print(f"  label agreement:        {same_label*100:.4f}%")
    if same_label < 0.9999:
        raise SystemExit("ONNX disagrees with torch on labels — investigate, do not ship")
    print("ONNX reproduces torch")

    # The preprocessing parameters go next to the weights — next to them and
    # automatically: retraining changes the intensity window, the spacing and
    # the patch, and forgetting to update them separately means a plausible
    # yet wrong result. A model update in production = replacing two files.
    if a.precision == "fp16":
        # Half precision is free here, measured on 20 held-out DentVoxel cases
        # against manual labels: 0.9613 versus 0.9619 for fp32, with nnU-Net
        # itself at 0.9610. fp16 even agrees with nnU-Net better (0.995 versus
        # 0.976) — it computes in half itself.
        # keep_io_types: input and output stay fp32, a Cast goes inside the graph.
        from onnxconverter_common import float16
        import warnings
        print("converting the graph to fp16 ...")
        m = onnx.load(a.out)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")   # warns about every tiny number
            m16 = float16.convert_float_to_float16(m, keep_io_types=True)
        onnx.save(m16, a.out)
        print(f"  file {os.path.getsize(a.out)/1e6:.0f} MB")
        sess = ort.InferenceSession(a.out, providers=["CPUExecutionProvider"])
        got16 = sess.run(None, {"input": x.numpy()})[0]
        agree = (ref.argmax(1) == got16.argmax(1)).mean()
        print(f"  label agreement with torch: {agree*100:.3f}%")
        if agree < 0.99:
            raise SystemExit("fp16 disagrees with torch — do not ship")

    cfg_path = os.path.splitext(a.out)[0] + ".json"
    with open(cfg_path, "w", encoding="utf-8") as f:
        cfg = make_config(plans, os.path.basename(a.out), a.classes, ck)
        cfg["precision"] = a.precision
        if a.extra_config:
            cfg.update(json.load(open(a.extra_config, encoding="utf-8")))
        json.dump(cfg, f, indent=2, ensure_ascii=False)
    print(f"preprocessing parameters -> {cfg_path}")


if __name__ == "__main__":
    main()
